version: '2.6'

services:
  cloud_app: 
    build: .
    command: rails s -b 0.0.0.0 
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    
  redis:
    image: redis:alpine 
    volumes:
      - redis:/data

  sidekiq:
    build: .
    volumes: 
      - .:/usr/src
    command: sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis

volumes: 
  redis:
  sidekiq: